name: rubygems

on:
  pull_request:

  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  rubygems:
    name: RubyGems on ${{ matrix.os }} (${{ matrix.ruby }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - macos-14
          - windows-2022

        ruby:
          - "3.3"
          - "3.4"
          - "4.0"

        include:
          - ruby: jruby-9.4.9.0
            os: ubuntu-24.04

          # - ruby: { name: truffleruby-24, value: truffleruby-24.1.0 }
          #   os: ubuntu-24.04

          - os: windows-2022
            ruby: mswin

          - os: ubuntu-24.04
            ruby: ruby-head

          - os: ubuntu-24.04
            ruby: truffleruby-head

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup ruby (Ubuntu/macOS)
        uses: ruby/setup-ruby@c4e5b1316158f92e3d49443a9d58b31d25ac0f8f # v1.306.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Configure bindgen
        shell: pwsh
        run: |
          echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
          echo "BINDGEN_EXTRA_CLANG_ARGS=$((gcm clang).source -replace "bin\clang.exe","include")" >> $env:GITHUB_ENV
        if: matrix.ruby == 'mswin'
      - name: Run Test
        run: bin/rake spec
        if: "!startsWith(matrix.ruby, 'truffleruby') && !startsWith(matrix.ruby, 'jruby')"
      - name: Run Test (JRuby)
        run: JRUBY_OPTS=--debug bin/rake spec
        if: startsWith(matrix.ruby, 'jruby')
      - name: Run Test (Truffleruby)
        run: TRUFFLERUBYOPT="--experimental-options --testing-rubygems" bin/rake spec
        if: startsWith(matrix.ruby, 'truffleruby')

    timeout-minutes: 20
